# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TVShows' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TVShows
  pod 'SVProgressHUD', '~> 2.2'
  # Pod for Networking
  pod 'Alamofire', '~> 4.7'
  # Coder and decoder for json
  pod 'CodableAlamofire', '~> 1.1'
end
